# -*- coding: utf-8 -*-
"""파이썬3주차.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lfFFx-B5j_rM3Kcpb16pUEsoxrWex4WS
"""

a =  [5, 5, 65, 34, 6, 67, 4]

print(a[:])

a = []
for i in range(0, 30, 3):
    a.append(i)

print(a)

numList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
res = []

for num in numList:
    if num == 8:
        break
    
    if num % 2 == 0:
        continue
    
    res.append(num)

print(res)

n = int(input("원하는 줄 개수"))
start = 0

for i in range(n):
  start += 1
  print("*" * start)

  if start == n
    break

n = int(input("원하는 줄 개수"))
start = 0

while start < n:
  start += 1
  print("*" * start)